import org.gradle.api.JavaVersion.VERSION_16

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.1.1/samples
 */

plugins {
    id("org.springframework.boot") version "2.5.5"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    java
}

group = "com.priyakdey"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = VERSION_16

repositories {
    mavenCentral()
}


dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<Test> {
    useJUnitPlatform() {
        includeTags("unit")     // Include all test cases which are tagged as "unit"
    }
}